version: '3.8'

services:
  api:
    build: .
    restart: always
    env_file:
      - keys/.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json
    ports:
      - "8000:8000"
    volumes:
      - ./keys/service_account.json:/app/service_account.json

  worker:
    build: .
    restart: always
    command: python cron.py
    env_file:
      - keys/.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json
    volumes:
      - ./keys/service_account.json:/app/service_account.json
