export const theme = {
    colors: {
        background: '#f0fcf8',
        onSurface: '#131e1b',
        primary: '#1a3c34',
        primaryContainer: '#c5eadf',
        secondary: '#b90c55',
        secondaryContainer: '#fe4d86',
        tertiary: '#1e2221',
        surfaceContainer: '#e5f0ec',
        surfaceContainerHigh: '#dfebe6',
        surfaceContainerLow: '#eaf6f2',
        surfaceContainerLowest: '#ffffff',
        outline: '#717976',
        outlineVariant: '#c1c8c4',
        onSurfaceVariant: '#414846',
        error: '#ba1a1a',
        vibrantPink: '#D10056',
    },
    spacing: {
        xs: 4,
        sm: 12,
        md: 24,
        lg: 40,
        xl: 64,
        gutter: 20,
        margin: 24,
    },
    roundness: {
        sm: 8,
        md: 12,
        lg: 16,
        xl: 24,
        full: 9999,
    },
    typography: {
        displayLg: {
            fontSize: 32,
            fontWeight: '700',
            lineHeight: 40,
            letterSpacing: -0.6,
        },
        headlineMd: {
            fontSize: 24,
            fontWeight: '600',
            lineHeight: 32,
            letterSpacing: -0.3,
        },
        bodyLg: {
            fontSize: 18,
            fontWeight: '400',
            lineHeight: 28,
        },
        bodyMd: {
            fontSize: 16,
            fontWeight: '400',
            lineHeight: 24,
        },
        labelSm: {
            fontSize: 13,
            fontWeight: '600',
            lineHeight: 18,
            letterSpacing: 0.5,
        },
    },
};
