export const theme = {
    colors: {
        background: '#fbf9f8',
        onSurface: '#1b1c1c',
        primary: '#556158',
        primaryContainer: '#e8f5e9',
        secondary: '#6b5a60',
        secondaryContainer: '#f4dce4',
        tertiary: '#3c6842',
        surfaceContainer: '#f0eded',
        surfaceContainerHigh: '#eae8e7',
        surfaceContainerLow: '#f2f4f2',
        outline: '#747873',
        outlineVariant: '#c3c8c2',
        onSurfaceVariant: '#434844',
        error: '#ba1a1a',
        vibrantPink: '#E6007A',
    },
    spacing: {
        xs: 4,
        sm: 12,
        md: 24,
        lg: 40,
        xl: 64,
        gutter: 16,
        margin: 24,
    },
    roundness: {
        sm: 4,
        md: 12,
        lg: 16,
        xl: 24,
        full: 9999,
    },
    typography: {
        displayLg: {
            fontSize: 32,
            fontWeight: '700',
            lineHeight: 40,
            letterSpacing: -0.6,
        },
        headlineMd: {
            fontSize: 24,
            fontWeight: '600',
            lineHeight: 32,
            letterSpacing: -0.3,
        },
        bodyLg: {
            fontSize: 18,
            fontWeight: '400',
            lineHeight: 28,
        },
        bodyMd: {
            fontSize: 16,
            fontWeight: '400',
            lineHeight: 24,
        },
        labelSm: {
            fontSize: 13,
            fontWeight: '600',
            lineHeight: 18,
            letterSpacing: 0.5,
        },
    },
};
